spring:
  application:
    name: eureka-server01
server:
  port: 8761                    
eureka:
  client:
    registerWithEureka: false   
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
security:
  basic:
    enabled: true
  user:
     name: wangjf
     #password: '{cipher}AQBBANdaI+QOb3OwoO4WOm0bDzr//yTSDTCW7i9NnqE35QGM2hhq41rnr6YaOaDv8ChjE+Kgd4RvpTTeMWTEldftfs25TopBhQfcD6u7y9+80tclFfkM4TRXj/oFr87ygnJgHhT6FpqILXZv09PlhMu4NCPEUWkKpPVwDyTXFemLDTg+6Uj9bIafZs0hKejdIGJ4Hnhah0Kn+ExC3mD+j/ye01DSWqYWzlG7jpevmijoq3pdZPPpGSMYsD7720bwBO8CVfLPWrtj40WtZqRdaN72aXnODIoJxVEqdPeznj/5/K7szONt3+obt0A8aDdzIv6jnNfpXred1YrbcudXrTIzkY6KRJ5cgUZtvHybMjVF71eVjTPCPxpAfv2YHARDWGM='
     password: 123
#--- 
#spring:
#   profiles: peer1                                 
#server:
#   port: 8761 
#eureka:
#   client:                                    
#      serviceUrl:
#         defaultZone: http://localhost:8762/eureka/ 
#--- 
#spring:
# profiles: peer2 
#server:
#   port: 8762 
#eureka:
#   client:
#     serviceUrl:
#        defaultZone: http://localhost:8761/eureka/
      