server:
  port: 8000
# spring.application.name 用于指定注册到Eureka Server上的应用名称
spring:
  application:
    name: eureka-provider
eureka:
  client:
    serviceUrl:
      defaultZone: http://wangjf:'{cipher}AQBBANdaI+QOb3OwoO4WOm0bDzr//yTSDTCW7i9NnqE35QGM2hhq41rnr6YaOaDv8ChjE+Kgd4RvpTTeMWTEldftfs25TopBhQfcD6u7y9+80tclFfkM4TRXj/oFr87ygnJgHhT6FpqILXZv09PlhMu4NCPEUWkKpPVwDyTXFemLDTg+6Uj9bIafZs0hKejdIGJ4Hnhah0Kn+ExC3mD+j/ye01DSWqYWzlG7jpevmijoq3pdZPPpGSMYsD7720bwBO8CVfLPWrtj40WtZqRdaN72aXnODIoJxVEqdPeznj/5/K7szONt3+obt0A8aDdzIv6jnNfpXred1YrbcudXrTIzkY6KRJ5cgUZtvHybMjVF71eVjTPCPxpAfv2YHARDWGM='@localhost:8761/eureka/
 #eureka.instance.prefer-ip-address  表示将自己的IP注册到Eureka Server上，
 #如果不配置,会将当前服务提供者所在的主机名注册到Eureka Server上。
  instance:
    prefer-ip-address: true