spring:
  application:
    name: eureka-server01
server:
  port: 8761                    
eureka:
  client:
    registerWithEureka: false   
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
security:
  basic:
    enabled: true
  user:
     name: wangjf
     password: 123

#--- 
#spring:
#   profiles: peer1                                 
#server:
#   port: 8761 
#eureka:
#   client:                                    
#      serviceUrl:
#         defaultZone: http://localhost:8762/eureka/ 
#--- 
#spring:
# profiles: peer2 
#server:
#   port: 8762 
#eureka:
#   client:
#     serviceUrl:
#        defaultZone: http://localhost:8761/eureka/
      