server:
  port: 8040
spring:
  application:
    name: eureka-zuul
eureka:
  client:
    service-url:
      defaultZone: http://wangjf:123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    
zuul:
  routes:
    eureka-provider: /provider/**
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
        timeout:
          enabled: false

